dependencies:
  audio_metadata_reader: ^1.1.0
  canvas_danmaku: ^0.2.6
  chewie:
    path: ./chewie-1.8.5
  cupertino_icons: ^1.0.6
  dart_des: ^1.0.2
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_lyric: ^2.0.4+6
  flutter_speed_dial: any
  flutter_subtitle: ^0.0.5
  http: null
  lpinyin: any
  lrc: any
  marquee: any
  flutter_secure_storage: any
  google_fonts: any
  ns_danmaku:
    git:
      ref: master
      url: https://github.com/xiaoyaocz/flutter_ns_danmaku.git
  path: null
  provider: ^6.0.5
  rxdart: ^0.27.7
  simple_gesture_detector: ^0.2.1
  vivysub_utils: ^0.2.0
  webdav_client: null
  xml: null
  intl: any
  castscreen: 
    path: ./castscreen-1.0.2
  dio: any
  smb_connect: ^0.0.9
dependency_overrides:
  audio_service:
    git:
      path: audio_service
      url: https://gitee.com/openharmony-sig/fluttertpc_audio_service.git
  audio_session:
    git:
      url: https://gitee.com/openharmony-sig/flutter_audio_session.git
  dart_libass:
    path: ./dart_libass-main
  file_picker_ohos:
    path: ./fluttertpc_file_picker/ohos
  file_selector:
    git:
      path: packages/file_selector/file_selector
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  fluttertoast:
    git: https://gitee.com/openharmony-sig/flutter_fluttertoast.git
  image_picker:
    path: ./image_picker/image_picker
  image_picker_platform_interface:
    path: ./image_picker/image_picker_platform_interface
  image_picker_ohos:
    path: ./image_picker/image_picker_ohos
  image_picker_android:
    path: ./image_picker/image_picker_android
  image_picker_ios:
    path: ./image_picker/image_picker_ios
  just_audio:
    git:
      path: just_audio
      url: https://gitee.com/openharmony-sig/fluttertpc_just_audio.git
  just_audio_background:
    git:
      path: just_audio_background
      url: https://gitcode.com/openharmony-sig/fluttertpc_just_audio.git
  just_audio_ohos:
    git:
      path: just_audio/ohos
      url: https://gitee.com/openharmony-sig/fluttertpc_just_audio.git
  media_info:
    git:
      url: https://gitee.com/openharmony-sig/fluttertpc_media_info.git
  mime: ^2.0.0
  path_provider:
    git:
      path: packages/path_provider/path_provider
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  screen:
    path: ./fluttertpc_screen/
  share_plus:
    git:
      path: packages/share_plus/share_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  shared_preferences:
    git:
      path: packages/shared_preferences/shared_preferences
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  sqflite:
    git:
      path: sqflite
      url: https://gitee.com/openharmony-sig/flutter_sqflite.git
  url_launcher:
    git:
      path: packages/url_launcher/url_launcher
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  video_player:
    path: ./video_player/video_player
  video_player_ohos:
    path: ./video_player/video_player_ohos
  video_player_platform_interface:
    path: ./video_player/video_player_platform_interface
  video_player_avfoundation:
    path: ./video_player/video_player_avfoundation
  video_thumbnail_ohos:
    git:
      path: ohos
      url: https://gitee.com/openharmony-sig/fluttertpc_video_thumbnail.git
  wakelock:
    git:
      path: wakelock
      url: https://gitee.com/openharmony-sig/flutter_wakelock.git
  wakelock_plus:
    git:
      path: wakelock_plus
      url: https://gitee.com/openharmony-sig/fluttertpc_wakelock_plus.git
  webview_flutter:
    git:
      path: packages/webview_flutter/webview_flutter
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  win32: 5.5.4
  # media_kit:
  #   path: ../media-kit-ohos/media_kit
  # media_kit_video:
  #   path: ../media-kit-ohos/media_kit_video
  # media_kit_libs_video:
  #   path: ../media-kit-ohos/libs/universal/media_kit_libs_video
  # media_kit_libs_ohos_video:
  #   path: ../media-kit-ohos/libs/ohos/media_kit_libs_ohos_video
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.4.0 <4.0.0'
flutter:
  assets:
  - Assets/10s_silence.wav
  - Assets/icon.png
  - Assets/privacy_policy.html
  - Assets/thanksfor.txt
  uses-material-design: true
name: aloeplayer
publish_to: none
version: 2.0.3+26
