dependencies:
  audio_metadata_reader: ^1.1.0
  canvas_danmaku: ^0.2.6
  chewie:
    path: ./chewie-1.8.5
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_subtitle: ^0.0.5
  http: null
  path: null
  provider: 6.1.2
  simple_gesture_detector: ^0.2.1
  vivysub_utils: ^0.2.0
  webdav_client: null
  xml: null
  ns_danmaku: 
    git: 
        url: https://github.com/xiaoyaocz/flutter_ns_danmaku.git
        ref: master
dependency_overrides:
  audio_service:
    git:
      path: audio_service
      url: https://gitee.com/openharmony-sig/fluttertpc_audio_service.git
  audio_session:
    git:
      url: https://gitee.com/openharmony-sig/flutter_audio_session.git
  file_picker_ohos:
    path: ./fluttertpc_file_picker/ohos
  file_selector:
    git:
      path: packages/file_selector/file_selector
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  fluttertoast:
    git: https://gitee.com/openharmony-sig/flutter_fluttertoast.git
  image_picker:
    git:
      path: packages/image_picker/image_picker
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  just_audio:
    git:
      path: just_audio
      url: https://gitee.com/openharmony-sig/fluttertpc_just_audio.git
  just_audio_ohos:
    git:
      path: just_audio/ohos
      url: https://gitee.com/openharmony-sig/fluttertpc_just_audio.git
  media_info:
    git:
      url: https://gitee.com/openharmony-sig/fluttertpc_media_info.git
  mime: ^2.0.0
  path_provider:
    git:
      path: packages/path_provider/path_provider
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  screen:
    path: ./fluttertpc_screen/
  share_plus:
    git:
      path: packages/share_plus/share_plus
      url: https://gitee.com/openharmony-sig/flutter_plus_plugins.git
  shared_preferences:
    git:
      path: packages/shared_preferences/shared_preferences
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  url_launcher:
    git:
      path: packages/url_launcher/url_launcher
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  video_player:
    path: ./video_player/video_player
  video_player_ohos:
    path: ./video_player/video_player_ohos
  video_thumbnail_ohos:
    git:
      path: ohos
      url: https://gitee.com/openharmony-sig/fluttertpc_video_thumbnail.git
  wakelock:
    git:
      path: wakelock
      url: https://gitee.com/openharmony-sig/flutter_wakelock.git
  wakelock_plus:
    git:
      path: wakelock_plus
      url: https://gitee.com/openharmony-sig/fluttertpc_wakelock_plus.git
  webview_flutter:
    git:
      path: packages/webview_flutter/webview_flutter
      url: https://gitee.com/openharmony-sig/flutter_packages.git
  win32: 5.5.4
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.4.0 <4.0.0'
flutter:
  assets:
  - Assets/
  uses-material-design: true
name: aloeplayer
publish_to: none
version: 1.0.3+15
